const TYPE_EXTERNAL_URL = 1
const TYPE_SHARED_FILE = 2
const TYPE_COLLABORATIVE_FOLDER = 3

export {
  TYPE_EXTERNAL_URL,
  TYPE_SHARED_FILE,
  TYPE_COLLABORATIVE_FOLDER
}

export default {
  TYPE_EXTERNAL_URL,
  TYPE_SHARED_FILE,
  TYPE_COLLABORATIVE_FOLDER
}
