
const nbActivityPerPage = 10

const TYPE_FILE_CREATION = 1
const TYPE_FILE_MODIFICATION = 2
const TYPE_FILE_MOVE = 3
const TYPE_FILE_DELETION = 4
const TYPE_FOLDER_CREATION = 5
const TYPE_FOLDER_MODIFICATION = 6
const TYPE_FOLDER_MOVE = 7
const TYPE_FOLDER_DELETION = 8
const TYPE_ADD_MEMBERSHIP = 9
const TYPE_REMOVE_MEMBERSHIP = 10
const TYPE_PENDING_RENVOI = 11
const TYPE_SCHOOL_RENVOI = 12
const TYPE_NEWS = 13
const TYPE_HOMEWORK = 14
const TYPE_SESSION = 15
const TYPE_EXPIRED_GROUP = 16

export default {
  nbActivityPerPage,
  TYPE_FILE_CREATION,
  TYPE_FILE_MODIFICATION,
  TYPE_FILE_MOVE,
  TYPE_FILE_DELETION,
  TYPE_FOLDER_CREATION,
  TYPE_FOLDER_MODIFICATION,
  TYPE_FOLDER_MOVE,
  TYPE_FOLDER_DELETION,
  TYPE_ADD_MEMBERSHIP,
  TYPE_REMOVE_MEMBERSHIP,
  TYPE_PENDING_RENVOI,
  TYPE_SCHOOL_RENVOI,
  TYPE_NEWS,
  TYPE_HOMEWORK,
  TYPE_SESSION,
  TYPE_EXPIRED_GROUP
}
