const TYPE_TEXT_CONTENT = 1
const TYPE_AUDIO_CONTENT = 2
const TYPE_LINK_CONTENT = 3
const TYPE_VIDEO_CONTENT = 4
const TYPE_FILE_CONTENT = 5
const TYPE_H5P_CONTENT = 6

export default {
  TYPE_TEXT_CONTENT,
  TYPE_AUDIO_CONTENT,
  TYPE_LINK_CONTENT,
  TYPE_VIDEO_CONTENT,
  TYPE_FILE_CONTENT,
  TYPE_H5P_CONTENT
}
