// TODO not export all in one time to improve performances
const icons = {
  file: require('@assets/documentIcons/icon-file.svg'),
  folder: require('@assets/documentIcons/icon-folder.svg'),
  folderOpen: require('@assets/documentIcons/icon-folder.svg'),
  extensions: {
    ggb: require('@assets/documentIcons/geogebra.svg'),
    gif: require('@assets/documentIcons/image.svg'),
    html: require('@assets/documentIcons/wisiwig.svg'),
    jpg: require('@assets/documentIcons/image.svg'),
    jpeg: require('@assets/documentIcons/image.svg'),
    mind: require('@assets/documentIcons/mind-map.svg'),
    mp3: require('@assets/documentIcons/audio.svg'),
    mp4: require('@assets/documentIcons/video.svg'),
    mpg: require('@assets/documentIcons/video.svg'),
    mov: require('@assets/documentIcons/video.svg'),
    odp: require('@assets/documentIcons/odp.svg'),
    ppt: require('@assets/documentIcons/odp.svg'),
    sxi: require('@assets/documentIcons/odp.svg'),
    pptx: require('@assets/documentIcons/odp.svg'),
    csv: require('@assets/documentIcons/ods.svg'),
    ods: require('@assets/documentIcons/ods.svg'),
    sxc: require('@assets/documentIcons/ods.svg'),
    tsv: require('@assets/documentIcons/ods.svg'),
    xls: require('@assets/documentIcons/ods.svg'),
    xlsx: require('@assets/documentIcons/ods.svg'),
    odt: require('@assets/documentIcons/odt.svg'),
    doc: require('@assets/documentIcons/odt.svg'),
    sxw: require('@assets/documentIcons/odt.svg'),
    docx: require('@assets/documentIcons/odt.svg'),
    pdf: require('@assets/documentIcons/pdf.svg'),
    png: require('@assets/documentIcons/image.svg'),
    sb3: require('@assets/documentIcons/scratch.svg'),
    wav: 'music',
    zip: 'file-archive'
  },
  options: {
    addToFavorites: 'star',
    copyWebdavUrl: require('@/assets/options/icon_webdav.svg'),
    copyUrl: require('@/assets/options/icon_duplicate.svg'),
    download: require('@/assets/options/icon_download.svg'),
    delete: require('@/assets/icon_trash.svg'),
    delete_white: require('@/assets/icon_trash_white.svg'),
    deleteDefinitely: ['far', 'trash-alt'],
    details: require('@/assets/options/icon_details.svg'),
    duplicate: require('@/assets/options/icon_duplicate.svg'),
    import: require('@assets/options/icon_fichier_ajout.svg'),
    forward: require('@/assets/options/icon_share.svg'),
    forward_white: require('@/assets/options/icon_share_white.svg'),
    leave: require('@/assets/options/icon_leave.svg'),
    markAsRead: require('@/assets/options/icon_mark_as_read.svg'),
    markAsRead_white: require('@/assets/options/icon_mark_as_read_white.svg'),
    move: require('@/assets/options/icon_move.svg'),
    modify: require('@/assets/options/icon_edit_texte.svg'),
    modify_white: require('@/assets/options/icon_edit_texte_white.svg'),
    new: require('@assets/options/icon_add.svg'),
    newFolder: require('@assets/options/icon_dossier_ajout.svg'),
    openFile: require('@assets/documentIcons/icon-file.svg'),
    paste: require('@/assets/options/icon_duplicate.svg'),
    permissions: require('@/assets/options/icon_permissions.svg'),
    share: require('@/assets/options/icon_share.svg'),
    rename: require('@/assets/options/icon_edit_texte.svg'),
    refresh: require('@/assets/options/icon_refresh.svg'),
    reply: require('@/assets/options/icon_answer.svg'),
    reply_white: require('@/assets/options/icon_answer_white.svg'),
    replyAll: require('@/assets/options/icon_answer_all.svg'),
    replyAll_white: require('@/assets/options/icon_answer_all_white.svg'),
    upload: require('@/assets/options/icon_upload.svg')
  }
}

export {
  icons
}
