const ENTRY_TYPE_INFORMATION = 1
const ENTRY_TYPE_AUTHORIZATION = 2
const ENTRY_TYPE_OBSERVATION = 3
const NONE_FILTERS = -1

export default {
  ENTRY_TYPE_INFORMATION,
  ENTRY_TYPE_AUTHORIZATION,
  ENTRY_TYPE_OBSERVATION,
  NONE_FILTERS
}
