
const quickSearchPaginationSize = 10

const TYPE_NEWS = 1
const TYPE_NEWS_FILE = 2
const TYPE_MESSAGE = 3
const TYPE_MESSAGE_FILE = 4
const TYPE_FOLDER = 5
const TYPE_FILE = 6
const TYPE_COLLABORATIVE_FILE = 7
const TYPE_COLLABORATIVE_FOLDER = 8
const TYPE_PROGRESSION = 9
const TYPE_PROGRESSION_COURSE = 10
const TYPE_PROGRESSION_HOMEWORK = 11
const TYPE_PROGRESSION_FILE = 12

export {
  quickSearchPaginationSize
}

export default {
  TYPE_NEWS,
  TYPE_NEWS_FILE,
  TYPE_MESSAGE,
  TYPE_MESSAGE_FILE,
  TYPE_FOLDER,
  TYPE_FILE,
  TYPE_COLLABORATIVE_FILE,
  TYPE_COLLABORATIVE_FOLDER,
  TYPE_PROGRESSION,
  TYPE_PROGRESSION_COURSE,
  TYPE_PROGRESSION_HOMEWORK,
  TYPE_PROGRESSION_FILE
}
